# Generated by Django 5.1 on 2024-08-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_ticket_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(default='Unassigned', max_length=100),
        ),
    ]
