# Generated by Django 5.1 on 2024-09-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0004_ticket_last_updated_by_ticket_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='action_taken',
            field=models.TextField(default='No action taken yet', null=True),
        ),
    ]
